# Generated by Django 6.0 on 2025-12-05 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='айди')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('region', models.CharField(max_length=255, verbose_name='регион')),
                ('resource_type', models.CharField(choices=[('lake', 'Озеро'), ('canal', 'Канал'), ('reservoir', 'Водохранилище')], max_length=20, verbose_name='тип водоёма')),
                ('water_type', models.CharField(choices=[('fresh', 'Пресная'), ('nonfresh', 'Непресная')], max_length=20, verbose_name='пресная/непресная')),
                ('fauna', models.BooleanField(default=False, verbose_name='наличие фауны')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='дата паспорта')),
                ('technical_condition', models.PositiveSmallIntegerField(default=1, verbose_name='техническое состояние')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='пдф файл')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='уровень приоритета')),
            ],
        ),
    ]
