# Generated by Django 6.0 on 2025-12-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterobject',
            options={'ordering': ('-id',), 'verbose_name': 'водный ресурс', 'verbose_name_plural': 'водные ресурсы'},
        ),
    ]
