# Generated by Django 6.0 on 2025-12-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_waterobject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterobject',
            name='region',
            field=models.CharField(choices=[('akmola', 'Акмолинская'), ('aktobe', 'Актюбинская'), ('almaty_region', 'Алматинская'), ('atyrau', 'Атырауская'), ('east_kz', 'Восточно-Казахстанская'), ('zhambyl', 'Жамбылская'), ('west_kz', 'Западно-Казахстанская'), ('karaganda', 'Карагандинская'), ('kostanay', 'Костанайская'), ('kyzylorda', 'Кызылординская'), ('mangystau', 'Мангистауская'), ('pavlodar', 'Павлодарская'), ('north_kz', 'Северо-Казахстанская'), ('turkestan', 'Туркестанская'), ('ulytau', 'Улытауская'), ('zhetysu', 'Жетысуская'), ('astana', 'г. Астана'), ('almaty', 'г. Алматы'), ('shymkent', 'г. Шымкент')], max_length=50, verbose_name='регион'),
        ),
    ]
