# Generated by Django 6.0 on 2025-12-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_waterobject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterobject',
            name='technical_condition',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='техническое состояние'),
        ),
    ]
